# Default values for shop-backend

replicaCount: 3  # Number of pod replicas

image:
  repository: strm/helloworld-http  # Container image repository
  tag: latest  # Container image tag

service:
  port: 80  # Port exposed by the container

livenessProbe:
  path: /  # Liveness probe path
  port: 80  # Port for liveness probe
  initialDelaySeconds: 10  # Delay before liveness probe starts
  periodSeconds: 10  # Frequency of liveness probe
  timeoutSeconds: 1  # Timeout for liveness probe
  failureThreshold: 3  # Failure threshold for liveness probe

readinessProbe:
  path: /  # Readiness probe path
  port: 80  # Port for readiness probe
  initialDelaySeconds: 10  # Delay before readiness probe starts
  periodSeconds: 1  # Frequency of readiness probe
  timeoutSeconds: 1  # Timeout for readiness probe
  failureThreshold: 2  # Failure threshold for readiness probe

cronjob:
  schedule: "*/30 * * * *"  # Cron job schedule
  image:
    repository: busybox  # Image for the cron job
    tag: latest  # Tag for the cron job image
  command: ["/bin/sh", "-c"]  # Command to run in the cron job
  args: ["echo Hello World"]  # Arguments for the command
